### PR TITLE
Fix noshipping by still checking shipping on products

### LINKED ISSUE #286: NOSHIPPING=0 always.
After update to v1.4.0 we got an error from Paypal about wrong shipping address. The product is virtual and doesn't require shipping. I believe that's wrong behavior and needs to be  fixed.

### PR DESCRIPTION
**Pull request by bor0**
Fixes #286.

### CODE REVIEW

File: includes/class-wc-gateway-ppec-plugin.php [hunk 1]
```diff
@@ -372,4 +372,21 @@ public function plugin_action_links( $links ) {
 
 		return array_merge( $plugin_links, $links );
 	}
+
+	/**
+	 * Check if shipping is needed for PayPal.
+	 *
+	 * @since 1.4.1
+	 *
```
Comment (roykho) [inline includes/class-wc-gateway-ppec-plugin.php]: Would be good to put a `@version` here per our standards doc.
