### PR TITLE
Save transaction data of Reference transactions in _woo_pp_txnData meta

### LINKED ISSUE #612: PayPal Checkout Refund Failure: "Already Refunded/No Amount to Refund"
# Issue Overview
When attempting to process a refund with Paypal Checkout for an order that had not previously been touched, an error occurred stating that the transaction had already been refunded and there was no amount left to refund. Neither of these statements is true in this scenario.

## Issue Production/Reproduction
Here are the steps we took to produce & re-produce this error.

1. Today (August 21st, 2019) we attempted to process a refund in WooCommerce using the "Refund Via Paypal Checkout" button. It was only a partial refund, `$8.01` out of a `$57.73 ` order.

2. We input the refund amount as usual and attempted to process the refund (which correctly read as `8.01` on the "Refund with Paypal Checkout" button )

3. A dialogue came up asking us if we were sure we wanted to continue as this could not be undone. We said "OK".

4. The Processing animation began and after a short while a dialogue box popped up saying:
```
Refund Error: All transactions have been fully refunded. There is no amount left to refund.
```

This is not the case. No refund has ever been processed on this order and the order details confirm this.

5. We logged into our PayPal account and can also confirm that no refund has been manually processed there for this order. To reiterate, there is no record of any refund ever taking place in WooCommerce or PayPal for the order in question.

As an additional note, I believe this issue started after our upgrade to the latest versions of WooCommerce and PayPal Checkout. I am providing additional helpful details as well as a stack trace of the actual error that occurred when the refund threw the error.

We attempted this multiple times from multiple admin accounts and from 2 different office locations (totally different IP addresses) and got the same result.

## Error & System Details
**Error Screenshot**
Screenshot 2019-08-21 10 16 49

**Here's a stack trace of the error in Sentry**
[https://sentry.io/share/issue/32ec34a1e73e4a46aa0764abe969934e/](https://sentry.io/share/issue/32ec34a1e73e4a46aa0764abe969934e/)

**Brief System Status**
Wordpress: `5.2.2`
WooCommerce: `3.7.0`
Paypal Checkout Gateway: `1.6.17`

### PR DESCRIPTION
**Pull request by menakas**
**Issue**: #612

---

### Description
Whenever a Reference Transaction is done( via a renewal order of WC Subscriptions or a scheduled order of Autoship ) the transaction details are not stored in `_woo_pp_txnData` meta like it is done with Express Checkout. Because of this, the Reference Transaction orders throw errors while refund.

To fix this, the details required for refund are saved in the `_woo_pp_txnData`  meta for Reference Transactions too.

### Steps to test:

1. Create a subscription product and purchase it.
1. Try to refund the parent order. This should fo through without any issues.
1. Now, process a renewal order on the subscription. 
1. Try to refund the renewal order. On this branch, it will go through but on any other branch, it will throw an error.
1. Also note that the renewal order has an entry for `_woo_pp_txnData` meta in `wp_postmeta` table in the database on this branch, while there is no such entry made on other branches.

Closes #612 .

### CODE REVIEW

**Comment by chickenn00dle** [comment]
Nice work @menakas 🙌

This does resolve the issue for me for newer reference transactions, but I noticed that any prior orders missing the relevant `_woo_pp_txnData` data still return the same error. I'm not sure if there is anything we can do about that considering the `refundable_txns` data was never set for these, but do you think we could at least improve the error messaging there?

Here is what I see when attempting to refund an order affected by this issue that was created prior to this fix:

Screen Shot 2020-04-09 at 12 45 47

Also, I noticed the logic for creating this data here is repeated in [WC_Gateway_PPEC_Checkout_Handler::do_payment()](https://github.com/woocommerce/woocommerce-gateway-paypal-express-checkout/blob/5d5c036bf172215fc0e12ff09b604ded613d1b4f/includes/class-wc-gateway-ppec-checkout-handler.php#L922). Do you think it is worth extracting this behavior into its own method for reusability? Honestly, I'm not certain of how practical that would be, so I would love your thoughts on that.

**Comment by menakas** [comment]
Thanks @chickenn00dle

Both are valid points.

I've added 9ca344b for giving an appropriate error message.

>I noticed the logic for creating this data here is repeated

Earlier, I was uncertain if the logic can be abstracted as Express Checkout was using a Payment Details object but for Reference Transactions, I am using the response array.

Now that you pointed out, I dug slightly beyond that to find that the Payment Details object gets populated from the response array. So, yes, it is indeed possible. 8d3ae4a does that.

Let me know what you think.

File: includes/functions.php [hunk 1]
```diff
@@ -154,3 +154,57 @@ function wc_gateway_ppec_get_transaction_fee( $order ) {
...
+ * Saves the transaction details from the transaction response into a post meta.
+ *
+ * @since 2.0
+ *
+ * @param object $order    Order for which the transaction was made
+ * @param object $response Response from a transaction
+ * @param object $prefix   A prefix string which is empty for Reference Transactions and is 'PAYMENTINFO_0_' for Express Checkout
+ * @return void
+ */
+function wc_gateway_ppec_save_transaction_data( $order, $response, $prefix = '' ) {
```
Comment (chickenn00dle) [inline includes/functions.php:168]: This is a very small detail, so feel free to disregard it. But what do you think about renaming `$response` here to something else like `$transaction` or `$order_details` for clarity?

This may be because I'm still relatively new to this codebase, but without context, I would have to look through this function code to get an idea of what is meant.

**Comment by chickenn00dle** [comment]
Awesome! 

I can confirm this still does the trick, and the error is much clearer for orders missing the refundable data.

I left a comment above which is not a blocker. So if you think it's not relevant, this LGTM.

**Comment by menakas** [comment]
@chickenn00dle 
Done.

**Comment by menakas** [comment]
@chickenn00dle 
I've changed the base branch to master. Now, this must be good to go.

**Comment by chickenn00dle** [comment]
Awesome! Thanks for making the change. 🙌
