### PR TITLE
Fix error 10426 when coupons are used

### LINKED ISSUE #562: PayPal API errors 10426 and 10413 with "Number of Decimals" set to 4 and discount coupon applied
**Summary**
When WooCommerce is configured to calculate prices with 4 decimals (woocommerce_price_num_decimals), applying a percentage discount coupon leads to `PAYMENTREQUEST_0_ITEMAMT` being sent with 4 decimals. This causes PayPal API errors [10426 ](https://developer.paypal.com/docs/classic/api/errors/#10426) and [10413](https://developer.paypal.com/docs/classic/api/errors/#10413).
Without a coupon applied there are no issues with using 4 decimals.

**Steps to reproduce**
1. Install WooCommerce and WooCommerce PayPal Express Checkout
2. Set Woocommerce Options in "WooCommerce->Settings"

    - In the "General" tab set "Number of Decimals" to 4
    - In the "Tax" tab set "Prices Entered With Tax" to "Yes, I will enter prices inclusive of tax"

3. Add this code to functions.php or custom plugin:
```php
//Sets parameter for price display to only show 2 decimals regardless of "Number of Decimals" option
function myslug_decimals_price_args($args)
{
    $args['decimals'] = 2;
    return $args;
}
add_filter('wc_price_args', 'myslug_decimals_price_args', 10, 1);
```
4. Create a "Percentage discount" coupon
5. Apply the coupon
6. Try to checkout via the PayPal Smart Button or in the checkout via PayPal

**Expected behaviour:**
The payment should work when a coupon is applied regardless of the "Number of Decimals" option. All values should be rounded to 2 or 0 decimals (depending on currency) before being sent to the PayPal API. 

**Actual behaviour**
`[PAYMENTREQUEST_0_ITEMAMT]` is being sent with 4 decimals. This causes PayPal API errors [10426 ](https://developer.paypal.com/docs/classic/api/errors/#10426) and [10413](https://developer.paypal.com/docs/classic/api/errors/#10413).
The $discounts variable is not rounded before it gets added to `round( WC()->cart->cart_contents_total, $decimals )` or respectively `round( $order->get_subtotal(), $decimals )` in
[WC_Gateway_PPEC_Client::_get_details_from_cart()](https://github.com/woocommerce/woocommerce-gateway-paypal-express-checkout/blob/054e0f3cd1e03e249da009d2f121c1b689f4f815/includes/class-wc-gateway-ppec-client.php#L454)
and
[WC_Gateway_PPEC_Client::_get_details_from_order()](https://github.com/woocommerce/woocommerce-gateway-paypal-express-checkout/blob/054e0f3cd1e03e249da009d2f121c1b689f4f815/includes/class-wc-gateway-ppec-client.php#L652)
causing the $details['total_item_amount'] to have 4 decimals.

**Probably related issues**
#337 
#517 

**Additional Information**
The combination of  "Number of Decimals" set to 4, "Prices Entered With Tax" set to "Yes, I will enter prices inclusive of tax" and
```php
//Sets parameter for price display to only show 2 decimals regardless of "Number of Decimals" option
function myslug_decimals_price_args($args)
{
    $args['decimals'] = 2;
    return $args;
}
add_filter('wc_price_args', 'myslug_decimals_price_args', 10, 1);
```
is a way to force WooCommerce to Calculate taxes more precisely without having to enter prices without taxes.
This also allows 
```php
add_filter( 'woocommerce_adjust_non_base_location_prices', '__return_false' )
```
to be used, which has the effect that for different tax rates in different regions always the same gross price is charged, without rounding errors in tax calculations.
Without this combination of settings we also couldn't maintain price calculation integrity between WooCommerce and our ERP.

wc_gateway_ppec log:
```
04-25-2019 @ 11:23:57 - WC_Gateway_PPEC_Client::_request: remote request to https://api-3t.sandbox.paypal.com/nvp with params: Array
(
    [LOGOIMG] => 
    [HDRIMG] => 
    [PAGESTYLE] => 
    [BRANDNAME] => blackbeards
    [RETURNURL] => https://blckbrds.com/kasse?woo-paypal-return=true
    [CANCELURL] => https://blckbrds.com/warenkorb?woo-paypal-cancel=true
    [LANDINGPAGE] => Login
    [SOLUTIONTYPE] => Sole
    [PAYMENTREQUEST_0_PAYMENTACTION] => sale
    [PAYMENTREQUEST_0_INSURANCEAMT] => 0
    [PAYMENTREQUEST_0_HANDLINGAMT] => 0
    [PAYMENTREQUEST_0_CUSTOM] => 
    [PAYMENTREQUEST_0_INVNUM] => 
    [PAYMENTREQUEST_0_CURRENCYCODE] => EUR
    [PAYMENTREQUEST_0_AMT] => 18.68
    [PAYMENTREQUEST_0_ITEMAMT] => 15.6911
    [PAYMENTREQUEST_0_SHIPPINGAMT] => 0
    [PAYMENTREQUEST_0_TAXAMT] => 2.99
    [PAYMENTREQUEST_0_SHIPDISCAMT] => 0
    [NOSHIPPING] => 0
    [EMAIL] => kontakt-buyer2@elias.works
    [PAYMENTREQUEST_0_SHIPTONAME] => Test Test
    [PAYMENTREQUEST_0_SHIPTOSTREET] => Teststreet14
    [PAYMENTREQUEST_0_SHIPTOSTREET2] => 
    [PAYMENTREQUEST_0_SHIPTOCITY] => Testcity
    [PAYMENTREQUEST_0_SHIPTOSTATE] => 
    [PAYMENTREQUEST_0_SHIPTOZIP] => 12234
    [PAYMENTREQUEST_0_SHIPTOCOUNTRYCODE] => DE
    [PAYMENTREQUEST_0_SHIPTOPHONENUM] => 
    [L_PAYMENTREQUEST_0_NAME0] => Bartöl All-In-One 50ml
    [L_PAYMENTREQUEST_0_DESC0] => 
    [L_PAYMENTREQUEST_0_QTY0] => 1
    [L_PAYMENTREQUEST_0_AMT0] => 20.92
    [L_PAYMENTREQUEST_0_NAME1] => Discount
    [L_PAYMENTREQUEST_0_DESC1] => 
    [L_PAYMENTREQUEST_0_QTY1] => 1
    [L_PAYMENTREQUEST_0_AMT1] => -5.23
    [METHOD] => SetExpressCheckout
    [VERSION] => 120.0
    [USER] => kontakt-facilitator_api1.elias.works
    [PWD] => 3SY2RNH26CJHDJAQ
    [SIGNATURE] => AhohO4-KgSw3.irCt33CzXOvr3DUATtHzkFUm47mmbFSQE.cGkYwBXNh
)

04-25-2019 @ 11:23:58 - WC_Gateway_PPEC_Client::_process_response: acknowleged response body: Array
(
    [TIMESTAMP] => 2019-04-25T09:23:58Z
    [CORRELATIONID] => f8a67226f1961
    [ACK] => Failure
    [VERSION] => 120.0
    [BUILD] => 000000
    [L_ERRORCODE0] => 10426
    [L_ERRORCODE1] => 10413
    [L_SHORTMESSAGE0] => Transaction refused because of an invalid argument. See additional error messages for details.
    [L_SHORTMESSAGE1] => Transaction refused because of an invalid argument. See additional error messages for details.
    [L_LONGMESSAGE0] => Item total is invalid.
    [L_LONGMESSAGE1] => The totals of the cart item amounts do not match order amounts.
    [L_SEVERITYCODE0] => Error
    [L_SEVERITYCODE1] => Error
)
```

### LINKED ISSUE #633: Applying coupons to some prices still results in error 10426
**Describe the bug**
When a percentage coupon is applied to a price where the result would end up having more than 2 decimal places, the checkout fails

**To Reproduce**
1. Add a product with price 89.99
2. Create a coupon with 99% discount
3. Attempt to go through PayPal checkout product from 1. with coupon from 2.
4. The checkout fails

**Expected behavior**
No error should occur.

**Additional context**
Related to #526, 2456855-zen, 1964049-zen and others.

### PR DESCRIPTION
**Pull request by marcinbot**
Fixes #562 
Fixes #633 

Rounds the `total_item_amount` and `order_total` after applying the discounts.

To test:
1. Add a product with price 89.99
2. Create a coupon with 99% discount
3. Attempt to go through PayPal checkout product from 1. with coupon from 2.
4. The PP window should open and you should be able to complete the checkout
or:
1. Repeat steps 1-2 above
2. Set the number of decimal places to 4
3. Checkout should still work

### CODE REVIEW

File: includes/class-wc-gateway-ppec-client.php [hunk 1]
```diff
@@ -460,7 +460,7 @@ protected function _get_details_from_cart() {
 		$discounts     = WC()->cart->get_cart_discount_total();
 
 		$details = array(
-			'total_item_amount' => round( WC()->cart->cart_contents_total, $decimals ) + $discounts,
+			'total_item_amount' => round( WC()->cart->cart_contents_total + $discounts, $decimals ),
```
Comment (v18) [inline includes/class-wc-gateway-ppec-client.php]: Why do we need to add rounding in `_get_details_from_cart()` and `_get_details_from_order`? I'm asking because the `total_item_amount` gets rounded correctly in `get_details` which is called from both of these functions.

**Comment by v18** [comment]
This PR solves the issue for me. I left a comment on where we need to round.

I was also able to find a "fun" bug where the total_line_items differ between the cart and order, and therefore they add unnecessary line items like this:

weird-line-items

It's not related to this PR, so not a blocker, and I'll write up a new issue for next time.

**Comment by v18** [comment]
The branch conflicts need to be resolved - they're related to https://github.com/woocommerce/woocommerce-gateway-paypal-express-checkout/pull/583

File: includes/class-wc-gateway-ppec-client.php (hunk 1 above)
Comment (marcinbot) [reply includes/class-wc-gateway-ppec-client.php]: I think it's better to be consistent and safe in case the function gets used anywhere else without the subsequent call to `get_details`. Any amount sent to paypal can only have up to 2 decimal places and it's best to follow that convention, at least in the client class.

**Comment by v18** [comment]
👌 looks good 🚢
