### PR TITLE
Do not apply conditional for 0 >= cart total when we're on the order …

### LINKED ISSUE #264: Resend Customer invoice Email - pay link not working
### EXPLANATION OF THE ISSUE

When sending a customer invoice from Woocommerce order page, the  pay link in the email does not work if Paypal Express Checkout is the only enabled payment method. Error message received is "Sorry, it seems that there are no available payment methods for your location. Please contact us if you require assistance or wish to make alternate arrangements." 

### STEPS TO REPRODUCE THE ISSUE

1. Make sure Paypal Express Checkout is the only enabled payment method. 
2. Select an unpaid order and choose "Resend Customer invoice" in "Order actions". 
3. Click the "pay" link in the email. 
4. In the "pay for order"-page under payment methods you only receive "Sorry, it seems that there are no available payment methods for your location. Please contact us if you require assistance or wish to make alternate arrangements."

### SYSTEM STATUS

<details>
```
Tried on multiple systems, both 2.x and 3.x and it appears on all of them no matter what theme is used or plugins are enabled / disabled.

Plugin: WooCommerce PayPal Express Checkout Gateway
Plugin Version 1.2.1 | By WooCommerce

WC version:		3.0.6
WP version:		4.7.4
WP multisite:		–
WP memory limit:		256 MB
WP debug mode:		
WP cron:		
Language:		en_US
 
Server environment
Server info:		Apache/2.4.18 (Ubuntu)
PHP version:		7.0.15-0ubuntu0.16.04.4
PHP post max size:		8 MB
PHP time limit:		30
PHP max input vars:		1000
cURL version:		7.47.0, OpenSSL/1.0.2g
SUHOSIN installed:		–
MySQL version:		5.7.18
Max upload size:		2 MB
Default timezone is UTC:		

Database
WC database version:		3.0.6

```
</details>

### PR DESCRIPTION
**Pull request by bor0**
…pay screen

Fixes #264.

### CODE REVIEW

File: includes/class-wc-gateway-ppec-checkout-handler.php [hunk 1]
```diff
@@ -446,7 +446,7 @@ public function maybe_disable_other_gateways( $gateways ) {
 		}
 
 		// If the cart total is zero (e.g. because of a coupon), don't allow this gateway
-		if ( is_cart() || is_checkout() ) {
+		if ( is_cart() || ( is_checkout() && ! is_checkout_pay_page() ) ) {
```
Comment (gedex) [inline includes/class-wc-gateway-ppec-checkout-handler.php]: Looking at this check, I couldn't figure out why. Maybe we could add note/reference on the reasoning?

**Comment by bor0** [comment]
@gedex one more round please.
