### PR TITLE
If cart total is 0 do not show PP buttons in mini cart

### LINKED ISSUE #635: Smart payment buttons appear when the product is free
**Describe the bug**
When the product is free, the smart payment buttons still appear on the product page. If shipping is also free (or not selected by the customer before) clicking on the button will throw error 10525

**To Reproduce**
1. Add a free product
2. Add free shipping and disable paid shipping methods
3. Open the product page
4. Attempt to click on the smart payment button

**Expected behavior**
We should not show the buttons in this scenario, since PayPal API does not allow for zero-cost transactions.

Should also handle the variable products.

### PR DESCRIPTION
**Pull request by menakas**
Fixes #635 

When a free product with free shipping is in the cart, the smart payment buttons are displayed in the mini cart. PayPal does not allow for zero payment and so these buttons should not be displayed.

I added an additional check for the cart total value not being 0 for displaying the PP buttons in the mini cart.

**Steps to test**
1. Create a product Z that has price set to 0.
2. Create two shipping methods for your region - free shipping and flat rate.
3. Enable Free shipping and disable flat rate shipping.
4. Add a product P that has a price > 0. Check the mini cart. The Smart Payment buttons are displayed.
5. Add Z to the cart. Remove P. Check the mini cart. On master, the Smart Payment buttons are displayed while on this branch, they are not displayed.
6. Disable Free shipping and enable Flat rate shipping.
7. Add a product P that has a price > 0. Check the mini cart. The Smart Payment buttons are displayed.
8. Add Z to the cart. Remove P. Check the mini cart. On both master and this branch, the Smart Payment buttons are displayed because there is a shipping cost involved.

Closes #635.

### CODE REVIEW

File: includes/class-wc-gateway-ppec-cart-handler.php [hunk 1]
```diff
@@ -351,7 +351,7 @@ public function display_mini_paypal_button() {
 		$settings = wc_gateway_ppec()->settings;
 
 		// billing details on checkout page to calculate shipping costs
-		if ( ! isset( $gateways['ppec_paypal'] ) || 'no' === $settings->cart_checkout_enabled || 0 === WC()->cart->get_cart_contents_count() ) {
+		if ( ! isset( $gateways['ppec_paypal'] ) || 'no' === $settings->cart_checkout_enabled || 0 === WC()->cart->get_cart_contents_count() || '0.00' === WC()->cart->get_total( 'edit' ) ) {
```
Comment (james-allan) [inline includes/class-wc-gateway-ppec-cart-handler.php]: To avoid the possibility of this var type changing in the future, and then failing on this strict string condition, I think we should use `WC()->cart->needs_payment()` instead.

Comment (menakas) [reply includes/class-wc-gateway-ppec-cart-handler.php]: Good idea. Pushed a commit with the change.

**Comment by james-allan** [comment]
LGTM 👍
