### PR TITLE
Fix free subscription initial purchases using PayPal Smart Buttons

### LINKED ISSUE #700: Subscriptions with $0 initial payment don't redirect to "Confirm your PayPal Order" page
### Describe the bug
While testing https://github.com/woocommerce/woocommerce-gateway-paypal-express-checkout/pull/698 I noticed a slight difference in behaviour when you purchase a non $0 product using the PayPal Smart Buttons found on the Product or Cart Pages compared to a $0 Subscriptions (i.e. one with a trial)

When purchasing a product > $0 (can be simple or subscription product) the usual flow is you are redirected to PayPal to authenticate a future payment (with a token and payerID given by PayPal), and then return back to a "Confirm your PayPal Order" page to finalise/confirm payment.

Notice the URL contains a `Token` and a `PayerID`.

When you purchase a Subscription with $0 upfront cost (trial or synced), the customer properly goes to PayPal to authorize payment, but when they return, they go back to the checkout page and then have to select PayPal Checkout again and fill in their card details or login a second time.

Here's a screencast of the two different cases starting with the non-zero purchase: https://d.pr/v/5DL48y

---

The tl;dr version is $0 purchases don't have a `PayerID`. I think this is causing the [`has_active_session()`](https://github.com/woocommerce/woocommerce-gateway-paypal-express-checkout/blob/07041bb6142ca39eb0e6267a268d2a2b5923f784/includes/class-wc-gateway-ppec-checkout-handler.php#L652-L659) function to return false which leads to the "Confirm your PayPal Order" page never being used even though we have a payment token.

### To reproduce

1. Enable Smart Buttons setting
1. Enable Smart Buttons on either Cart or Product pages
1. Add a subscription with a free trial to your cart
1. Click on the PayPal Smart button on the cart page
1. Complete the PayPal payment form
1. Notice you're redirected to the regular checkout page even though we have a `token` in the URL from PayPal
1. Notice the checkout still has every other gateway options listed (FYI Stripe shouldn't be there)
1. Choose PayPal Checkout and notice you need to enter your card details again

### Expected behavior

Because we have authorized the payment and authenticated with PayPal and have a token present, we should be redirected straight to the "Confirm your PayPal Order" page to finalise payment.

I think this is because the `has_active_session()` function requires a `PayerID` to exist.

We may also need to update `maybe_return_from_paypal()` to make sure it's handling orders with $0 payment, similarly to what is being done in https://github.com/woocommerce/woocommerce-gateway-paypal-express-checkout/pull/698

**Environment (please complete the following information):**
 - WordPress Version 5.3.2
 - WooCommerce Version 4.0

### PR DESCRIPTION
**Pull request by james-allan**
**Issue**: #700

---

### Description

When purchasing subscription products whose initial price is $0 (free trials etc) with PayPal Smart Buttons, when you return to the store, you aren't placed on the checkout with an active PayPal Session like you would when purchasing other products. This PR fixes that.

### Steps to test:

0. If you don't have one, create a subscription product with a free trial.
1. Go to the free trial product's single product page.
1. Click the PayPal (yellow) payment button.
1. Log in to PayPal and complete the steps.
1. When you return to the store:
    - On `master` you will be placed on the normal checkout page where you will need to fill out the checkout, select a payment gateway etc.
    - On this branch, you will be placed on the Pay for order special checkout page with only PPEC selected.

Completing the PayPal checkout completes the order and similar to the normal checkout just sends the request to create a billing agreement and then completes the order. 

### Documentation

- [ ] This PR needs documentation (has the "Documentation" label).

Closes #700

### CODE REVIEW

File: includes/class-wc-gateway-ppec-admin-handler.php [hunk 1]
```diff
@@ -153,22 +153,27 @@ public function maybe_capture_charge( $order ) {
 	 * @param int $order_id
 	 */
 	public function capture_payment( $order_id ) {
-		$order  = wc_get_order( $order_id );
-		$old_wc = version_compare( WC_VERSION, '3.0', '<' );
+		$order = wc_get_order( $order_id );
```
Comment (james-allan) [inline includes/class-wc-gateway-ppec-admin-handler.php]: Just a note on these changes. I noticed while testing that when I completed the checkout I would get the following PayPal Request and Response. 

```
WC_Gateway_PPEC_Client::_request: remote request to https://api-3t.sandbox.paypal.com/nvp with params: Array
(
    [TRANSACTIONID] => 
    [METHOD] => GetTransactionDetails
    [VERSION] => 120.0
    [USER] => ....business.example.com
    [PWD] => ...
    [SIGNATURE] => ...
)

WC_Gateway_PPEC_Client::_process_response: acknowleged response body: Array
(
    [ADDRESSOWNER] => PayPal
    [ADDRESSSTATUS] => None
    [TIMESTAMP] => 2020-03-24T02:39:16Z
    [CORRELATIONID] => f010a41f9b40e
    [ACK] => Failure
    [VERSION] => 120.0
    [BUILD] => 53802284
    [L_ERRORCODE0] => 10011
    [L_SHORTMESSAGE0] => Invalid transaction id value
    [L_LONGMESSAGE0] => A transaction id is required
    [L_SEVERITYCODE0] => Error
    [PENDINGREASON] => None
    [REASONCODE] => None
    [L_TAXABLE0] => false
)
```

I narrowed it down to this function which is trying to work out if we need to capture an authorized payment. Because there's no payment required, there's no transaction ID and therefore when we were trying to get the transaction details to determine if it needed capture we'd send an empty ID. 

These orders don't need auth and capture so when there's no transaction ID, don't continue. 

You can replicate this error on `master` by simply purchasing a free trial subscription with the latest changes from #698.

**Comment by mattallan** [comment]
Thanks @james-allan ! LGTM :+1:
